force-app/main/default/objects/Anken__c/Anken__c.object-meta.xml
<CustomObject>
    <label>案件</label>
    <nameField>
        <label>案件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anken__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>AnkenToAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>緊急度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>至急</fullName>
            </value>
            <value>
                <fullName>急</fullName>
            </value>
            <value>
                <fullName>中</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>応募者</label>
    <nameField>
        <displayFormat>AP-{YYYYMM}-{0000}</displayFormat>
        <label>応募者名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>姓</description>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>社員</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>社員名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>応募者</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>社員</relationshipLabel>
    <relationshipName>EmployeeToApplicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ankenserchcontorllertest.cls
@istest
public class ankenserchcontorllertest {

    static testMethod void unitTest01(){
        Applicant__c app =new Applicant__c();
        app.FirstName__c='太郎';
        insert app;
        
        Employee__c em = new Employee__c();
        em.FirstName__c=app.FirstName__c;
        em.LastName__c=app.LastName__c;
        insert em;
        
        Anken__c anken = new anken__c();
        anken.Account__c = app.id;
        anken.Level__c = '至急';
        insert anken;
       
        Test.startTest();
        PageReference pageRef = Page.AnkenSearch;
        system.debug('test em.id = ' + em.Id);
        
        pageRef.getParameters().put('id',em.Id);
        Test.setCurrentPage(pageRef);
        AnkenSearchController2 ctrl = new AnkenSearchController2();
        ctrl.init();
        Test.stopTest();        
        
    }
    
    
    
}