force-app/main/default/objects/Anken__c/Anken__c.object-meta.xml
<CustomObject>
    <label>案件</label>
    <nameField>
        <label>案件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>社員</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>社員名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>年齢</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/BigMonthPrice__c.field-meta.xml
<CustomField>
    <fullName>BigMonthPrice__c</fullName>
    <label>最大提案単価</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmployeeDivision__c.field-meta.xml
<CustomField>
    <fullName>EmployeeDivision__c</fullName>
    <label>社員区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>正社員</fullName>
            </value>
            <value>
                <fullName>契約社員</fullName>
            </value>
            <value>
                <fullName>パート</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/JapaneseLevel__c.field-meta.xml
<CustomField>
    <fullName>JapaneseLevel__c</fullName>
    <label>日本語レベール</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ビジネス</fullName>
            </value>
            <value>
                <fullName>日常会話</fullName>
            </value>
            <value>
                <fullName>作業会話</fullName>
            </value>
            <value>
                <fullName>仕様書読み</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>女性、</fullName>
            </value>
            <value>
                <fullName>男性</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/SmallMonthPrice__c.field-meta.xml
<CustomField>
    <fullName>SmallMonthPrice__c</fullName>
    <label>最小提案単価</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/StartJobDay__c.field-meta.xml
<CustomField>
    <fullName>StartJobDay__c</fullName>
    <label>入場可能時間</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EmploySearchController.cls
public with sharing class EmploySearchController {

    public String employResultList { get; set; }

    // 社員情報
    public List<Anken__c> ankenList {get; set;}
    public List<Employee__c> EmployeeList {get; set;}
    
    public String employeename {get; set;}

    public Boolean showDetail {get; set;}
    // システムエラーフラグ
    public Boolean isSystemErrorFlg {get; set;}
    // 件数制限
    private Integer limitInt = 1000;
    // 1ページにあたり件数
    private Integer pageSize = 50;
    // offset
    private Integer offsetInt = 0;
    // コンストラクタ
    public EmploySearchController() {
        this.employeename = '林田';
        this.isSystemErrorFlg = false;
    }
    /*
    * 機能 ：初期化
    * @param ：なし
    * @return：なし
     */
    
    public PageReference Init() {
        employeeList = [SELECT ID, FirstName__c, Sex__c,Age__c,EmployeeDivision__c,
        SmallMonthPrice__c,BigMonthPrice__c,JapaneseLevel__c,StartJobDay__c 
        FROM Employee__c ];
        
        ankenList = [SELECT ID, Name FROM Anken__c ];
        
        System.debug(employeeList[0].FirstName__c);
        return null;
    }
    
        /*
    * 機能 ：初期化
    * @param ：なし
    * @return：なし
     */
    
    public List<Employee__c> searchEmployeeList() {
       
        
       String parameter = System.currentPageReference().getParameters().get('FirstName__c');
        System.debug('1111111' + parameter);   
        String query = '';
        query += ' SELECT ';
        query += '  Id ';
        query += ' ,Name ';
        query += ' ,FirstName__c';
        query += ' ,Sex__c';
        query += ' ,Age__c';
        query += ' ,EmployeeDivision__c';
        query += ' ,SmallMonthPrice__c';
        query += ' ,BigMonthPrice__c';
        query += ' ,JapaneseLevel__c';
        query += ' ,StartJobDay__c ';
        query += ' FROM ';
        query += ' Employee__c';
        query += ' ORDER BY Name ASC ';
        query += ' LIMIT 200 ';
       return  database.query(query);

    }

}