force-app/main/default/objects/AddressMaster__c/AddressMaster__c.object-meta.xml
<CustomObject>
    <label>住所マスタ</label>
    <nameField>
        <label>住所CD</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressMaster__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>住所詳細</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee1__c/Employee1__c.object-meta.xml
<CustomObject>
    <label>社員マスタ</label>
    <nameField>
        <displayFormat>No-{000000}</displayFormat>
        <label>社員NO</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee1__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <label>住所１</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee1__c/fields/AddressCD__c.field-meta.xml
<CustomField>
    <fullName>AddressCD__c</fullName>
    <label>住所CD</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee1__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee1__c/fields/ShimeiKanji__c.field-meta.xml
<CustomField>
    <fullName>ShimeiKanji__c</fullName>
    <label>氏名（漢字）</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee1__c/fields/ShimeiKatakana__c.field-meta.xml
<CustomField>
    <fullName>ShimeiKatakana__c</fullName>
    <label>氏名（カタカナ）</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployHandlerTest.cls
@isTest
public class EmployHandlerTest {
    // Utility method that can be called by Apex tests to create price book entries.
    
     @testSetup 
     static void setup() {
        // Create common test accounts
        Employee1__c employeeIns = new Employee1__c();
        employeeIns.AddressCD__c ='2250045';
        employeeIns.Mail__c  ='test@gmail.com';
        employeeIns.ShimeiKatakana__c ='フジワラ'; 
        employeeIns.ShimeiKanji__c ='藤原';
        insert employeeIns; 
        AddressMaster__c addressMaster= new AddressMaster__c();
        addressMaster.name='2250030';
        addressMaster.Address__c='テスト住所';
               
    }
    @isTest 
    static void AfterUpdateTest() {
        // First, set up test price book entries.
        // Insert a test product.
        
        Employee1__c employee = [select id, AddressCD__c,Address1__c from Employee1__c where ShimeiKanji__c ='藤原']; 
        System.debug(employee);
        employee.AddressCD__c = '2250023';
        System.debug(employee.AddressCD__c);
        Test.startTest();
        update  employee;
        Employee1__c  employee2 = [select id, AddressCD__c,Address1__c from Employee1__c where ShimeiKanji__c ='藤原'];
		System.debug(employee2.Address1__c);
		System.assertEquals(employee2.Address1__c,'テスト住所');  
		Test.stopTest();
        // Next, perform some tests with your test price book entries.
    }
}